
server:
  port: 20100

logging:
  config: classpath:logback-custom.xml

spring:
  datasource:
    # MySQL8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/data_badminton?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: ^password*

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 结合logback输出到日志文件


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.badminton.tool.web
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: false
  setting:
    language: zh_cn

wx:
  jscode2session_url: https://api.weixin.qq.com/sns/jscode2session
  appid: wx736f2ce46f1621e5
  secret: dabb7967dff80251c7057dc278a64b5f
  grant_type: authorization_code